### ISSUE TITLE
Migrate mediawiki to a wiki running on AWS

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/aws-infra#2]
Currently we are running mediawiki on https://wiki.openttd.org
This is difficult to maintain for various of reasons:
- It has poor integration with SSOs:
  - LDAP has bad documentation and is unclear how maintained the plugin is; this depends on when you look this up.
  - OAuth2 (GitHub) integration is .. euh .. a thing to figure out. There is a plugin (WSOAuth) that does this, but development of these plugins is weird and often unclear if they are production worthy
- It requires a beefy database to work properly
  - Although most pages can be served semi-static, it renders them constantly. Of course this can be cached, but this shows this software was not created in recent years. It is build on old ideas and foundations.
- Upgrading is often challenging and non-trivial
  - Despite the best efforts of mediawiki, it turns out it is not a matter of bumping the version in most cases
- Maintaining the `LocalSettings.php` has proven to be a challenge.

End result: mediawiki has been updated 3 times in 15 years. We need a better solution, that can also run on AWS more easily. Running mediawiki on AWS is not impossible, but requires a lot of resources.

Currently we are investigating Gollum as alternative, mostly as it nicely integrates with git.

**Comment by LordAro** [comment]
Done!
